#!/bin/bash

if [ "$EUID" -ne 0 ]
then 
	printf "\033[31;1mPlease Run As Root\033[0m\n"
	exit
fi


default() {
	sudo mv pluto /usr/bin/pluto
	printf "\033[32;1mPluto Added To Path!\033[0m\n"

	if [ -f "$HOME/.config" ]
	then
		mkdir ~/.config/pluto
		touch ~/.config/pluto/config
	else
		mkdir ~/.config
		mkdir ~/.config/pluto
		touch ~/.config/pluto/config
	fi

	printf "\n# This file was generated by pluto.sh\n\n" >> ~/.config/pluto/config
	printf "sel=rev\ntheme=default\n\n" >> ~/.config/pluto/config
	printf "show-hidden=false\n\n" >> ~/.config/pluto/config
	printf "exit=q\ndel=d\ntoggle-hidden=.\n\n" >> ~/.config/pluto/config
	
	printf "\033[32;1m~/.config/pluto Generated!\033[0m\n"
	mkdir ~/.config/pluto/themes
	printf "\033[32;1m~/.config/pluto/themes Created\033[0m\n"
	touch ~/.config/pluto/themes/default.plut
	printf"file=0\ndir=13\ncwd-color=0\ncwd-format=bold" > ~/.config/pluto/themes/default.plut
	touch ~/.config/pluto/themes/dolly.plut
	printf"file=221\ndir=245\ncwd-color=250\ncwd-format=bold" > ~/.config/pluto/themes/dolly.plut
	touch ~/.config/pluto/themes/dwarf.plut
	printf"file=250\ndir=53\ncwd-color=197\ncwd-format=bold" > ~/.config/pluto/themes/dwarf.plut
	touch ~/.config/pluto/themes/oxide.plut
	printf "file=209\ndir=245\ncwd-color=250\ncwd-format=bold" > ~/.config/pluto/themes/oxide.plut
	printf "\033[32;1mThemes Generated!\033[0m\n"
	printf "\033[34;1mInstallation Finished!\033[0m\n"
	exit
}

minimal() {
	sudo mv pluto /usr/bin/pluto
	printf "\033[32;1mPluto Added To Path!\033[0m\n"
	mkdir ~/.config/pluto
	touch ~/.config/pluto/config
	printf "\033[32;1m~/.plutorc Created!\033[0m\n"
	mkdir ~/.config/pluto/themes
	printf "\033[32;1m~/.pluto and ~/.pluto/themes Created\033[0m\n"
	printf "\033[34;1mInstallation Finished!\033[0m\n"
	exit
}

clear
printf "\n\t\033[0m1 \033[0m\033[34mDefault Install\033[0m\n\n"
printf "\t\033[0m2 \033[0m\033[34mMinimal Install\033[0m\n\n\n"
printf " Option: "
read -n1 opt

if [ "$opt" == "1"]
then
	default
elif [ "$opt" == "2" ]
then
	minimal

fi
